### ISSUE TITLE
安装界面无法使用触控板🌝

### ISSUE THREAD

**Issue by bukaixyz** [SuaveZhou/RedmiBook-Pro-14S-hackintosh#1]
![IMG_0303](https://github.com/SuaveZhou/RedmiBook-Pro-14S-hackintosh/assets/85857425/b1b2383f-0010-4829-9da6-1608678b7afc)

**Comment by SuaveZhou** [comment]
明天或者今天晚上我会更新触控板驱动
此次驱动实现触控板中断模式



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月04日 21:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |

**Comment by bukaixyz** [comment]
> 明天或者今天晚上我会更新触控板驱动
> 此次驱动实现触控板中断模式
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2023年07月04日 21:43 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.***> |
> | 主题 | [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

什么时候更新啊🌚🌚🌚

**Comment by SuaveZhou** [comment]
抱歉 我的梯子最近出问题 git上传不了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月07日 22:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |

明天或者今天晚上我会更新触控板驱动
此次驱动实现触控板中断模式

---- 回复的原邮件 ----
| 发件人 | @.> |
| 日期 | 2023年07月04日 21:43 |
| 收件人 | @.> |
| 抄送至 | @.***> |
| 主题 | [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: @.***>

什么时候更新啊🌚🌚🌚

**Comment by bukaixyz** [comment]
> 抱歉 我的梯子最近出问题 git上传不了
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2023年07月07日 22:52 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.***>***@***.***> |
> | 主题 | Re: [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |
> 
> 明天或者今天晚上我会更新触控板驱动
> 此次驱动实现触控板中断模式
> 
> ---- 回复的原邮件 ----
> | 发件人 | @.> |
> | 日期 | 2023年07月04日 21:43 |
> | 收件人 | @.> |
> | 抄送至 | @.***> |
> | 主题 | [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: @.***>
> 
> 什么时候更新啊🌚🌚🌚
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

https://hk.flycloud.cyou/auth/login

**Comment by bukaixyz** [comment]
> 抱歉 我的梯子最近出问题 git上传不了
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2023年07月07日 22:52 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.***>***@***.***> |
> | 主题 | Re: [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |
> 
> 明天或者今天晚上我会更新触控板驱动
> 此次驱动实现触控板中断模式
> 
> ---- 回复的原邮件 ----
> | 发件人 | @.> |
> | 日期 | 2023年07月04日 21:43 |
> | 收件人 | @.> |
> | 抄送至 | @.***> |
> | 主题 | [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: @.***>
> 
> 什么时候更新啊🌚🌚🌚
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

可以传到网盘上🌚 中共真是害死人了，搞网络封锁，全世界都用国际互联网 ，很多政府机构，总统，国际公司，组织都用推特 YouTube 就中共搞个不一样的🌝

**Comment by SuaveZhou** [comment]
今天下午更新 现在没在家 下午我更新后会通知你



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月08日 14:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |

抱歉 我的梯子最近出问题 git上传不了

---- 回复的原邮件 ----
| 发件人 | @.> |
| 日期 | 2023年07月07日 22:52 |
| 收件人 | @.> |
| 抄送至 | @.>@.> |
| 主题 | Re: [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |

明天或者今天晚上我会更新触控板驱动
此次驱动实现触控板中断模式

---- 回复的原邮件 ----
| 发件人 | @.> |
| 日期 | 2023年07月04日 21:43 |
| 收件人 | @.> |
| 抄送至 | @.***> |
| 主题 | [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: @.***>

什么时候更新啊🌚🌚🌚

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: @.***>

可以传到网盘上🌚 中共真是害死人了，搞网络封锁，全世界都用国际互联网 ，很多政府机构，总统，国际公司，组织都用推特 YouTube 就中共搞个不一样的🌝

**Comment by SuaveZhou** [comment]
> > 抱歉 我的梯子最近出问题 git上传不了
> > ---- 回复的原邮件 ----
> > | 发件人 | _**@**_._**> |
> > | 日期 | 2023年07月07日 22:52 |
> > | 收件人 | _**@**_.**_> |
> > | 抄送至 | _**@**_._**>**_@_**.**_> |
> > | 主题 | Re: [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |
> > 明天或者今天晚上我会更新触控板驱动
> > 此次驱动实现触控板中断模式
> > ---- 回复的原邮件 ----
> > | 发件人 | @.> |
> > | 日期 | 2023年07月04日 21:43 |
> > | 收件人 | @.> |
> > | 抄送至 | @.***> |
> > | 主题 | [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this thread.Message ID: @.***>
> > 什么时候更新啊🌚🌚🌚
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 可以传到网盘上🌚 中共真是害死人了，搞网络封锁，全世界都用国际互联网 ，很多政府机构，总统，国际公司，组织都用推特 YouTube 就中共搞个不一样的🌝

EFI已更新

**Comment by bukaixyz** [comment]
> > > 抱歉 我的梯子最近出问题 git上传不了
> 
> > > ---- 回复的原邮件 ----
> 
> > > | 发件人 | _**@**_._**> |
> 
> > > | 日期 | 2023年07月07日 22:52 |
> 
> > > | 收件人 | _**@**_.**_> |
> 
> > > | 抄送至 | _**@**_._**>**_@_**.**_> |
> 
> > > | 主题 | Re: [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |
> 
> > > 明天或者今天晚上我会更新触控板驱动
> 
> > > 此次驱动实现触控板中断模式
> 
> > > ---- 回复的原邮件 ----
> 
> > > | 发件人 | @.> |
> 
> > > | 日期 | 2023年07月04日 21:43 |
> 
> > > | 收件人 | @.> |
> 
> > > | 抄送至 | @.***> |
> 
> > > | 主题 | [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |
> 
> > > —
> 
> > > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > > You are receiving this because you are subscribed to this thread.Message ID: @.***>
> 
> > > 什么时候更新啊🌚🌚🌚
> 
> > > —
> 
> > > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > > You are receiving this because you commented.Message ID: _**@**_.***>
> 
> > 
> 
> > 可以传到网盘上🌚 中共真是害死人了，搞网络封锁，全世界都用国际互联网 ，很多政府机构，总统，国际公司，组织都用推特 YouTube 就中共搞个不一样的🌝
> 
> 
> 
> EFI已更新

为什么WiFi用不了啊🌝

**Comment by SuaveZhou** [comment]
Ventura版本可以使用 其他版本需要下载对应版本的网卡驱动
如果你的电脑不是intel网卡 wifi则无法使用



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月09日 11:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |

抱歉 我的梯子最近出问题 git上传不了

---- 回复的原邮件 ----

| 发件人 | @._**> |

| 日期 | 2023年07月07日 22:52 |

| 收件人 | @.**_> |

| 抄送至 | @.>@.> |

| 主题 | Re: [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |

明天或者今天晚上我会更新触控板驱动

此次驱动实现触控板中断模式

---- 回复的原邮件 ----

| 发件人 | @.> |

| 日期 | 2023年07月04日 21:43 |

| 收件人 | @.> |

| 抄送至 | @.***> |

| 主题 | [SuaveZhou/RedmiBook-Pro-14S-hackintosh] 安装界面无法使用触控板🌝 (Issue #1) |

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: @.***>

什么时候更新啊🌚🌚🌚

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you commented.Message ID: @.***>

可以传到网盘上🌚 中共真是害死人了，搞网络封锁，全世界都用国际互联网 ，很多政府机构，总统，国际公司，组织都用推特 YouTube 就中共搞个不一样的🌝

EFI已更新

为什么WiFi用不了啊🌝
